=== tera-arise/arise-data/sheets/VillagerDialog/VillagerDialog.xsd
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xmlns:dc="https://tera-arise.io/dc"
            xmlns="https://tera-arise.io/dc/VillagerDialog"
            targetNamespace="https://tera-arise.io/dc/VillagerDialog"
            xsi:schemaLocation="https://tera-arise.io/dc ../DataCenter.xsd"
            elementFormDefault="qualified">
    <xsd:complexType name="VillagerDialog"
                     dc:keys="huntingZoneId id">
        <xsd:sequence>
            <xsd:element name="Text" type="VillagerDialog_Text" minOccurs="0" maxOccurs="unbounded" />
        </xsd:sequence>

        <xsd:attribute name="huntingZoneId" type="xsd:int" use="required" />
        <xsd:attribute name="id" type="xsd:int" use="required" />
        <xsd:attribute name="voiceTypeId" type="xsd:int" />
    </xsd:complexType>

    <xsd:complexType name="VillagerDialog_Text">
        <xsd:sequence>
            <xsd:element name="Page" type="VillagerDialog_Text_Page" maxOccurs="unbounded" />
        </xsd:sequence>

        <xsd:attribute name="endSocial" type="xsd:int" />
        <xsd:attribute name="huntingZoneId" type="xsd:int" />
        <xsd:attribute name="id" type="xsd:int" use="required" />
        <xsd:attribute name="prevId" type="xsd:int" />
        <xsd:attribute name="villagerId" type="xsd:int" />
    </xsd:complexType>

    <xsd:complexType name="VillagerDialog_Text_Page">
        <xsd:simpleContent>
            <xsd:extension base="xsd:string">
                <xsd:attribute name="social" type="xsd:int" />
                <xsd:attribute name="voiceTypeId" type="xsd:int" />
            </xsd:extension>
        </xsd:simpleContent>
    </xsd:complexType>

    <xsd:element name="VillagerDialog" type="VillagerDialog" />
</xsd:schema>

=== tera-arise/arise-data/sheets/VillagerDialog/VillagerDialog-03010.xml
<VillagerDialog xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xsi:schemaLocation="https://vezel.dev/novadrop/dc/VillagerDialog VillagerDialog.xsd"
                id="8100"
                huntingZoneId="123"
                voiceTypeId="67"
                xmlns="https://vezel.dev/novadrop/dc/VillagerDialog">
    <Text id="3"
          huntingZoneId="123"
          endSocial="14"
          prevId="0"
          villagerId="8100">
        <Page social="4">Lots of people here show off how brave they are, and lots of them get hurt in the process. I was dispatched here to help them.</Page>
    </Text>
    <Text id="20"
          huntingZoneId="123"
          endSocial="14"
          prevId="0"
          villagerId="8100">
        <Page social="4">Lots of people here show off how brave they are, and lots of them get hurt in the process. I was dispatched here to help them.</Page>
    </Text>
    <Text id="21"
          huntingZoneId="123"
          endSocial="14"
          prevId="0"
          villagerId="8100">
        <Page social="4">Lots of people here show off how brave they are, and lots of them get hurt in the process. I was dispatched here to help them.</Page>
    </Text>
    <Text id="22"
          huntingZoneId="123"
          endSocial="14"
          prevId="0"
          villagerId="8100">
        <Page social="4">Lots of people here show off how brave they are, and lots of them get hurt in the process. I was dispatched here to help them.</Page>
    </Text>
    <Text id="23"
          huntingZoneId="123"
          endSocial="14"
          prevId="0"
          villagerId="8100">
        <Page social="4">Lots of people here show off how brave they are, and lots of them get hurt in the process. I was dispatched here to help them.</Page>
    </Text>
    <Text id="1"
          huntingZoneId="123"
          endSocial="14"
          prevId="0"
          villagerId="8100">
        <Page social="4">My clerical duties are for the Iron Order.</Page>
    </Text>
</VillagerDialog>
