=== tera-arise/arise-data/sheets/StrSheet_PremiumCompose/StrSheet_PremiumCompose.xsd
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xmlns:dc="https://tera-arise.io/dc"
            xmlns="https://tera-arise.io/dc/StrSheet_PremiumCompose"
            targetNamespace="https://tera-arise.io/dc/StrSheet_PremiumCompose"
            xsi:schemaLocation="https://tera-arise.io/dc ../DataCenter.xsd"
            elementFormDefault="qualified">
    <xsd:complexType name="StrSheet_PremiumCompose">
        <xsd:sequence>
            <xsd:element name="String" type="StrSheet_PremiumCompose_String" minOccurs="0" maxOccurs="unbounded" />
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="StrSheet_PremiumCompose_String">
        <xsd:attribute name="id" type="xsd:int" use="required" />
        <xsd:attribute name="string" type="xsd:string" use="required" />
    </xsd:complexType>

    <xsd:element name="StrSheet_PremiumCompose" type="StrSheet_PremiumCompose" />
</xsd:schema>

=== tera-arise/arise-data/sheets/StrSheet_PremiumCompose/StrSheet_PremiumCompose-00005.xml
<StrSheet_PremiumCompose xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://vezel.dev/novadrop/dc/StrSheet_PremiumCompose StrSheet_PremiumCompose.xsd" xmlns="https://vezel.dev/novadrop/dc/StrSheet_PremiumCompose">
    <String id="1" string="Cube - Tester_A" />
    <String id="2" string="Mystic Style Cube" />
    <String id="3" string="Rare Style Cube" />
    <String id="4" string="Serena's Cube" />
    <String id="5" string="Lion's Event Cube" />
    <String id="6" string="Eyhian's Skill Manual Cube" />
    <String id="7" string="Eclipes Festival Cube " />
    <String id="8" string="Kukran's Skill Manual Cube" />
    <String id="9" string="Cryptic Cube" />
    <String id="10" string="White Winter Cube" />
    <String id="11" string="Kurat's All-in-one Gray Underwear Cube" />
    <String id="12" string="Meruma's Silk Underwear Cube" />
    <String id="16" string="Wolf's Fang Cube " />
    <String id="19" string="Mystel Snowflake Cube" />
    <String id="23" string="Chief Maid's Secret Cube" />
    <String id="24" string="Ser Picks-a-lot's Cube" />
    <String id="25" string="Inherited Foreign Country Cube" />
    <String id="26" string="Lirinda's Weaving Kit Cube" />
    <String id="28" string="Peppu's Precious Cube" />
    <String id="35" string="Christmas in May Cube" />
    <String id="36" string="Inherited Foreign Country Clothes Cube" />
    <String id="37" string="Sharp Tiger Claw Cube" />
    <String id="38" string="Soccer Mania Tiger Cube" />
    <String id="39" string="Marcus's Special Cube" />
    <String id="42" string="Shocola's Precious Cube" />
    <String id="47" string="2014 Ainah's Style Cube" />
    <String id="48" string="2014 Aniel's Style Cube" />
    <String id="50" string="Litherus' Style Cube" />
    <String id="51" string="Tamer's Beast Cube" />
    <String id="54" string="Cube in Wonderland" />
    <String id="58" string="Two Oaks Ranch Animal Cube" />
    <String id="59" string="Jaeron's Zany Cube" />
    <String id="61" string="Returned Foreign Weapons Cube" />
    <String id="63" string="[Event] Meruma's Silk Ash Undergarments Cube (Superior)" />
    <String id="64" string="Pantoto's Qipao Cube" />
    <String id="66" string="2014 Christmas Cube" />
    <String id="67" string="2014 End of the Year Cube" />
    <String id="69" string="Kurat's All-in-one Gray Underwear Cube (Superior)" />
    <String id="70" string="Thaman's Oriental Dragon Mount Cube" />
    <String id="71" string="Trezi's Surprise Cube" />
    <String id="73" string="Cheniel's Oriental Costume Cube" />
    <String id="74" string="Lubunul's Backwards Time Accessory Cube" />
    <String id="76" string="New Style Combining Cube" />
    <String id="77" string="Tamel's Arcade Weapon Cube" />
    <String id="80" string="Marcus' New Animal Costume Cube" />
    <String id="83" string="Cube" />
    <String id="84" string="Semi the Fairy's Style Custome Cube" />
    <String id="85" string="Wild Tyrant's Cube" />
    <String id="86" string="Luna's Frilly Cube" />
    <String id="89" string="[Event] Durian's Secret Cube" />
    <String id="90" string="Fast Sportscar Cube" />
    <String id="91" string="" />
    <String id="92" string="" />
    <String id="93" string="" />
    <String id="94" string="Cursed Island's Shadow Hunter Weapon Cube" />
    <String id="96" string="[Promotion] Genya's Lace Underwear Cube" />
    <String id="97" string="Genya's Lace Underwear Cube" />
    <String id="98" string="Genya's Lace Underwear Cube (Superior)" />
    <String id="102" string="Frani's Insect Collection Cube" />
    <String id="103" string="[Promotion] Frani's Insect Collection Cube" />
    <String id="104" string="" />
    <String id="105" string="" />
    <String id="106" string="[Event] Full Moon Cube" />
    <String id="108" string="Zinji's Angel Wing Stash Cube" />
    <String id="109" string="Huchu's Pet Cube" />
    <String id="110" string="Red- Yellow Special Costume Cube" />
    <String id="111" string="Sushi Cat Cube" />
    <String id="112" string="Formal Party Suit Cube" />
    <String id="113" string="[Event] Iron Cube" />
    <String id="114" string="Chenie's Accessory Bundle Cube" />
    <String id="115" string="Chenie's Costume Bundle Cube" />
    <String id="116" string="Chenie's Riding Skill Bundle Cube" />
    <String id="117" string="Midian's Streetfighter Cube" />
    <String id="118" string="Chenie's Winter Hanbok Cube" />
    <String id="119" string="[Event] 5th Anniversary TERA Cube" />
    <String id="120" string="HYDRATH Costume Cube" />
    <String id="121" string="Plasma Weapon Cube" />
    <String id="122" string="Shadowlaced Weapon Cube" />
    <String id="123" string="Girl friend Cube" />
    <String id="124" string="[Girl friend] School Uniform_Sports Uniform Costume Cube" />
    <String id="125" string="Lorcia's Urban Hip Hop Cube" />
    <String id="126" string="Hello Kitty comprehensive gift Cube" />
    <String id="127" string="" />
    <String id="128" string="SWAT Cube" />
    <String id="129" string="" />
    <String id="130" string="" />
    <String id="131" string="" />
    <String id="132" string="" />
    <String id="135" string="" />
    <String id="136" string="" />
    <String id="142288" string="" />
    <String id="1001" string="Convert to obtain an Icegrip Weapon Skin." />
    <String id="1002" string="Convert for a chance at [Duck Bill] or [Kelsaik Mask]." />
    <String id="1003" string="Convert for a chance at [Afro], [Classic Feather Hat]." />
    <String id="1004" string="Convert for a chance at a party dress or a veil in black or white. " />
    <String id="1005" string="Convert for a chance at [Corinth Bronze Helmet] or [Apothecary Dye]." />
    <String id="1006" string="Convert for a chance at [Munchhausen] or [Gourmando]." />
    <String id="1007" string="Convert for a chance at [Unique: Blueberry Little Witch Costume]." />
    <String id="1008" string="Contains various items, such as Riding Skill: Harley and Riding Skill: Spotted Pig Tori." />
    <String id="1009" string="Contains rare items, such as [Unique] Noir Suit Outfit and Tattoo Two-piece Pants [Elin]." />
    <String id="1010" string="Contains rare items, such as [Unique] 2013 Santa Costume, Red Bunny Girl, and Red Running Togs." />
    <String id="1011" string="Acquire [Kurat's All-in-one Gray Underwear Cube] with 100% chance of success." />
    <String id="1012" string="Acquire [Meruma's Silk Underwear Cube] with 100% chance of success." />
    <String id="1015" string="Compose and acquire [Wind Wolf's Cube] with 100% chance of success." />
    <String id="1023" string="Infuse the item to obtain a Merolyn's Clothing Collection Box/Lienyn's Weapon Stash with a 100% chance." />
    <String id="1024" string="Infuse the item to obtain a Ser Picks-a-lot's Treasure Chest with a 100% chance." />
    <String id="1025" string="Infuse the item to obtain an Inherited Foreign Country Jewel Box with a 100% chance." />
    <String id="1026" string="Infuse the item to obtain a Lirinda's Beauty Box with a chance of obtaining up to 5 of them." />
    <String id="1028" string="Combine to obtain [Peppu's Jumpsuit &amp; Black Magic Box]. At certain rate, you may earn up to 5 boxes." />
    <String id="1035" string="Infuse this item to obtain [Christmas in May Box] with a chance of obtaining up to 5 of them." />
    <String id="1036" string="Infuse the item to obtain an [Inherited Foreign Country Clothes Box] with a chance of obtaining up to 5 of them." />
    <String id="1037" string="Infuse this item to obtain a [Blue Gaze White Tiger Box] with a chance of obtaining up to 5 of them." />
    <String id="1038" string="Infuse the item to obtain an Soccer Mania Tiger Box with a chance to obtain up to 5." />
    <String id="1039" string="Infuse this item to obtain [Marcus's Animal Costume Box] or [Marcus's Animal Mask Box] with a chance to win more than one box." />
    <String id="1042" string="Infuse this item to obtain Casilyn's Premium Noctenium Box with a chance to obtain more than one." />
    <String id="1047" string="Infuse this item to obtain [Ainah's 2014 Swimsuits Box] with a chance to obtain more than one." />
    <String id="1048" string="Infuse this item to obtain [Aniel's 2014 Swimsuit Box] with a chance to obtain more than one." />
    <String id="1050" string="Infuse this item to obtain [Litherus' Bounty Box] with a chance to win more than one." />
    <String id="1051" string="Infuse this item to obtain a [Tamer's Beast Box] or [Riding Skill: Regal Frostlion] with a chance of obtaining more than one." />
    <String id="1054" string="Infuse this item to obtain [Treasure Chest in Wonderland] or [Pink Flamingo Weapon Crate] with a chance to obtain more than one." />
    <String id="1058" string="Combine this item to obtain [Two Oaks Ranch Animal Box] with a chance to obtain more than one and may even obtain a special mount item." />
    <String id="1059" string="Combine this item to obtain Jaeron's Zany Working Clothes Box or special accessories with a chance to obtain more than one box." />
    <String id="1061" string="Combine this item to obtain [Returned Foreign Treasure Chest] or [Ancient Relic Weapon Crate] with a chance to obtain more than one box." />
    <String id="1063" string="Combine this item to obtain [Event] Meruma's Silk Ash Undergarments Box (Rare)." />
    <String id="1064" string="Combine this item to obtain Pantoto's Qipao Box or White Flower Headband with a chance to obtain more than one box." />
    <String id="1066" string="Can obtain  [2014 Christmas Mount Box], [2014 Christmas Costume Box] and other special mounts through combining items. May obtain more than one." />
    <String id="1067" string="Can obtain  [2014 Year's End And Beginning Box] through combining items. May obtain more than one." />
    <String id="1069" string="Can obtain the legend grad Kurat's All-in-One Ash Bodysuit through combining items." />
