=== tera-arise/arise-data/sheets/Synthesizers/Synthesizers.xsd
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xmlns:dc="https://tera-arise.io/dc"
            xmlns="https://tera-arise.io/dc/Synthesizers"
            targetNamespace="https://tera-arise.io/dc/Synthesizers"
            xsi:schemaLocation="https://tera-arise.io/dc ../DataCenter.xsd"
            elementFormDefault="qualified">
    <xsd:complexType name="Synthesizers">
        <xsd:sequence>
            <xsd:element name="Synthesizer" type="Synthesizers_Synthesizer" maxOccurs="unbounded" />
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="Synthesizers_Synthesizer">
        <xsd:sequence>
            <xsd:element name="SynthesizeItems" type="Synthesizers_Synthesizer_SynthesizeItems" />
            <xsd:element name="TargetItemList" type="Synthesizers_Synthesizer_TargetItemList" />
        </xsd:sequence>

        <xsd:attribute name="id" type="xsd:int" use="required" />
    </xsd:complexType>

    <xsd:complexType name="Synthesizers_Synthesizer_SynthesizeItems">
        <xsd:sequence>
            <xsd:element name="SynthesizeItem" type="Synthesizers_Synthesizer_SynthesizeItems_SynthesizeItem" maxOccurs="unbounded" />
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="Synthesizers_Synthesizer_SynthesizeItems_SynthesizeItem">
        <xsd:attribute name="itemTemplateId" type="xsd:int" use="required" />
    </xsd:complexType>

    <xsd:complexType name="Synthesizers_Synthesizer_TargetItemList">
        <xsd:sequence>
            <xsd:element name="TargetItem" type="Synthesizers_Synthesizer_TargetItemList_TargetItem" maxOccurs="unbounded" />
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="Synthesizers_Synthesizer_TargetItemList_TargetItem">
        <xsd:attribute name="amount" type="xsd:int" use="required" />
        <xsd:attribute name="itemTemplateId" type="xsd:int" use="required" />
    </xsd:complexType>

    <xsd:element name="Synthesizers" type="Synthesizers" />
</xsd:schema>

=== tera-arise/arise-data/sheets/Synthesizers/Synthesizers-00000.xml
<Synthesizers xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://vezel.dev/novadrop/dc/Synthesizers Synthesizers.xsd" xmlns="https://vezel.dev/novadrop/dc/Synthesizers">
    <Synthesizer id="200930">
        <SynthesizeItems>
            <SynthesizeItem itemTemplateId="200920" />
            <SynthesizeItem itemTemplateId="200920" />
        </SynthesizeItems>
        <TargetItemList>
            <TargetItem amount="500" itemTemplateId="1300" />
            <TargetItem amount="500" itemTemplateId="1301" />
            <TargetItem amount="500" itemTemplateId="1302" />
            <TargetItem amount="500" itemTemplateId="1303" />
            <TargetItem amount="500" itemTemplateId="81212" />
            <TargetItem amount="500" itemTemplateId="212982" />
        </TargetItemList>
    </Synthesizer>
    <Synthesizer id="200931">
        <SynthesizeItems>
            <SynthesizeItem itemTemplateId="200921" />
            <SynthesizeItem itemTemplateId="200921" />
        </SynthesizeItems>
        <TargetItemList>
            <TargetItem amount="500" itemTemplateId="1300" />
            <TargetItem amount="500" itemTemplateId="1301" />
            <TargetItem amount="500" itemTemplateId="1302" />
            <TargetItem amount="500" itemTemplateId="1303" />
            <TargetItem amount="500" itemTemplateId="81212" />
            <TargetItem amount="500" itemTemplateId="212982" />
        </TargetItemList>
    </Synthesizer>
    <Synthesizer id="200932">
        <SynthesizeItems>
            <SynthesizeItem itemTemplateId="200922" />
            <SynthesizeItem itemTemplateId="200922" />
        </SynthesizeItems>
        <TargetItemList>
            <TargetItem amount="500" itemTemplateId="1300" />
            <TargetItem amount="500" itemTemplateId="1301" />
            <TargetItem amount="500" itemTemplateId="1302" />
            <TargetItem amount="500" itemTemplateId="1303" />
            <TargetItem amount="500" itemTemplateId="81212" />
            <TargetItem amount="500" itemTemplateId="212982" />
        </TargetItemList>
    </Synthesizer>
    <Synthesizer id="209341">
        <SynthesizeItems>
            <SynthesizeItem itemTemplateId="200922" />
            <SynthesizeItem itemTemplateId="200922" />
        </SynthesizeItems>
        <TargetItemList>
            <TargetItem amount="500" itemTemplateId="1300" />
            <TargetItem amount="500" itemTemplateId="1301" />
            <TargetItem amount="500" itemTemplateId="1302" />
            <TargetItem amount="500" itemTemplateId="1303" />
            <TargetItem amount="500" itemTemplateId="81212" />
            <TargetItem amount="500" itemTemplateId="212982" />
        </TargetItemList>
    </Synthesizer>
    <Synthesizer id="200939">
        <SynthesizeItems>
            <SynthesizeItem itemTemplateId="200929" />
            <SynthesizeItem itemTemplateId="200929" />
        </SynthesizeItems>
        <TargetItemList>
            <TargetItem amount="1000" itemTemplateId="1300" />
            <TargetItem amount="1000" itemTemplateId="1301" />
            <TargetItem amount="1000" itemTemplateId="1303" />
        </TargetItemList>
    </Synthesizer>
    <Synthesizer id="139177">
        <SynthesizeItems>
            <SynthesizeItem itemTemplateId="1230" />
            <SynthesizeItem itemTemplateId="1230" />
            <SynthesizeItem itemTemplateId="1230" />
            <SynthesizeItem itemTemplateId="1230" />
            <SynthesizeItem itemTemplateId="1230" />
        </SynthesizeItems>
        <TargetItemList>
            <TargetItem amount="1000" itemTemplateId="1300" />
        </TargetItemList>
    </Synthesizer>
</Synthesizers>
